# Generated by Django 4.0.4 on 2022-06-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redondos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('año', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('musico', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=30)),
                ('cantidadPublico', models.IntegerField()),
            ],
        ),
    ]
