# Generated by Django 4.0.4 on 2022-06-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redondos_app', '0002_compactos_instrumentos_recitales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recitales',
            name='cantidadPublico',
        ),
        migrations.AddField(
            model_name='recitales',
            name='anecdota',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='recitales',
            name='apellido',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recitales',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recitales',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recitales',
            name='lugar',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
